Feature/check why sending scan failed #14
boschglobal/locator_ros_bridge pull request #16
Opened 2022-07-08 14:04 UTC by slaible

2022-07-08 14:06 UTC, slaible commented
Signed-off-by: Stefan Laible [stefan.laible@de.bosch.com](mailto:stefan.laible@de.bosch.com)

2022-07-11 08:56 UTC, kfabian commented on bosch_locator_bridge/include/bosch_locator_bridge/locator_bridge_node.hpp
> +  bool get_config_entry(const std::string & name, std::string & value) const;
Might it make sense to have this templated to for completness with set_config_entry? There is a Poco::Dynamic::Var::convert method which could be used.

2022-07-11 09:04 UTC, kfabian commented on bosch_locator_bridge/include/bosch_locator_bridge/sending_interface.hpp
> +  enum SendingStatus {SUCCESS, NO_CONNECTIONS, NOT_COMPLETED, RESET_EXCEPTION, IO_EXCEPTION};
Using enum class over a plain enum is preferred.

2022-07-11 09:32 UTC, kfabian requested changes

2022-07-11 09:32 UTC, kfabian commented on bosch_locator_bridge/src/locator_bridge_node.cpp
> +bool LocatorBridgeNode::set_config_entry(const std::string & name, const T & value) const
A function template must be defined in a header file.

2022-07-13 07:58 UTC, merged