Add server interface
boschglobal/locator_ros_bridge pull request #3
Opened 2021-11-11 14:39 UTC by robertwil

Extend the bridge by adding a additional node to access the server:

- list server maps
- dowload and save the map as ROS-conform .png + .yaml files for the map_server package

Signed-off-by: Robert Willeit <fkml@gmx.de>

2021-11-23 12:55 UTC, slaible requested changes
Only tiny changes requested. Otherwise great work!! Thanks a lot :-)

2021-11-23 12:55 UTC, slaible commented on bosch_locator_bridge/CMakeLists.txt
> +  src/locator_rpc_interface.cpp)
```suggestion
  src/locator_rpc_interface.cpp
  src/rosmsgs_datagram_converter.cpp
  src/server/server_bridge_node.cpp
  src/server/server_main.cpp)
```
Sort alphabetically

2021-11-23 12:55 UTC, slaible commented on bosch_locator_bridge/include/bosch_locator_bridge/server/server_bridge_node.hpp
> +  ~ServerBridgeNode();
```suggestion
  virtual ~ServerBridgeNode();
```

2021-11-23 12:57 UTC, slaible commented on bosch_locator_bridge/include/bosch_locator_bridge/server/server_bridge_node.hpp
> +  ~ServerBridgeNode();
Once merged, I will port it also to ROS 2.

2021-11-23 20:14 UTC, robertwil commented
Included your changes (via the browser interface and forgot to sign-off). Hope everything worked as expected, but it looks good.

2021-11-24 09:02 UTC, slaible approved these changes

2021-11-24 09:03 UTC, merged